
package br.univel.wsclient.venda;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VendaWS", targetNamespace = "http://webservices/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VendaWS {


    /**
     * 
     * @return
     *     returns br.univel.wsclient.venda.Venda
     * @throws IOException_Exception
     * @throws ServletException_Exception
     */
    @WebMethod
    @WebResult(name = "resultVenda", targetNamespace = "")
    @RequestWrapper(localName = "opVenda", targetNamespace = "http://webservices/", className = "br.univel.wsclient.venda.OpVenda")
    @ResponseWrapper(localName = "opVendaResponse", targetNamespace = "http://webservices/", className = "br.univel.wsclient.venda.OpVendaResponse")
    public Venda opVenda()
        throws IOException_Exception, ServletException_Exception
    ;

}
