
package br.univel.wsclient.crudproduto;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CadastroProdutoWSService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:8080/lab134155/CadastroProdutoWS?WSDL")
public class CadastroProdutoWSService
    extends Service
{

    private final static URL CADASTROPRODUTOWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CADASTROPRODUTOWSSERVICE_EXCEPTION;
    private final static QName CADASTROPRODUTOWSSERVICE_QNAME = new QName("http://webservices/", "CadastroProdutoWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/lab134155/CadastroProdutoWS?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CADASTROPRODUTOWSSERVICE_WSDL_LOCATION = url;
        CADASTROPRODUTOWSSERVICE_EXCEPTION = e;
    }

    public CadastroProdutoWSService() {
        super(__getWsdlLocation(), CADASTROPRODUTOWSSERVICE_QNAME);
    }

    public CadastroProdutoWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CADASTROPRODUTOWSSERVICE_QNAME, features);
    }

    public CadastroProdutoWSService(URL wsdlLocation) {
        super(wsdlLocation, CADASTROPRODUTOWSSERVICE_QNAME);
    }

    public CadastroProdutoWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CADASTROPRODUTOWSSERVICE_QNAME, features);
    }

    public CadastroProdutoWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CadastroProdutoWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CadastroProdutoWS
     */
    @WebEndpoint(name = "CadastroProdutoWSPort")
    public CadastroProdutoWS getCadastroProdutoWSPort() {
        return super.getPort(new QName("http://webservices/", "CadastroProdutoWSPort"), CadastroProdutoWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CadastroProdutoWS
     */
    @WebEndpoint(name = "CadastroProdutoWSPort")
    public CadastroProdutoWS getCadastroProdutoWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "CadastroProdutoWSPort"), CadastroProdutoWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CADASTROPRODUTOWSSERVICE_EXCEPTION!= null) {
            throw CADASTROPRODUTOWSSERVICE_EXCEPTION;
        }
        return CADASTROPRODUTOWSSERVICE_WSDL_LOCATION;
    }

}
